define([], function() {
  return {
    "SwiperOptions": "Swiper Options",
    "GeneralGroupName": "General",
    "EnableNavigation":"Enable navigation",
    "EnablePagination":"Enable pagination",
    "SlidesPerWiew": "Slides per view",
    "AutoplayGroupName": "Autoplay",
    "EnableAutoplay": "Enable autoplay",
    "DelayAutoplay": "Delay autoplay",
    "Miliseconds": "Miliseconds",
    "DisableAutoplayOnInteraction": "Disable autoplay on interaction",
    "AdvancedGroupName": "Advanced",
    "SlidesPerGroup": "Slides per group",
    "SpaceBetweenSlides": "Space between slides",
    "InPixels": "In pixels",
    "EnableGrabCursor": "Enable grab cursor",
    "EnableLoop": "Enable loop",
    "SourceList":"Source List",
    "DataSourceGroupName":"Data Source",
    "ImageColumnName":"Image Column Name",
    "TitleColumnName":"Title Column Name",
    "FilterColumnName":"Filter Column Name",
    "OrderBy":"Order By Column Name", 
    "IsAsending":"Order by Asending?(State true or false)",
    "SelectTop":"Number of Top Records to select",
    "ShowCategoryFilter":"Show Category Filter",
    "ShowLatestFilter":"Show Latest Filter",
    "RedirectURL":"Redirect URL"
  }
});